version: '3'
services:
  web:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - redis-server
      - visits
  visits:
    build:
      context: ./visits
    ports:
      - '8081:8081'
    environment:
      - REDIS_HOST=redis-server
    volumes:
      - /app/node_modules
      - ./visits:/app
    depends_on:
      - redis-server
  redis-server:
    image: 'redis'
  tests:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]